# Generated by Django 3.0.3 on 2020-02-07 15:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('plate_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('license_num', models.CharField(max_length=200)),
                ('v_type', models.CharField(max_length=200)),
                ('num_of_passengers', models.IntegerField()),
                ('special_info', models.TextField(blank=True, max_length=200, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ride accross whole rides', primary_key=True, serialize=False)),
                ('dst_addr', models.CharField(max_length=200)),
                ('arrive_time', models.DateTimeField()),
                ('special_request', models.TextField(blank=True, max_length=200, null=True)),
                ('v_type', models.CharField(max_length=200)),
                ('plate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_passengers', models.PositiveIntegerField(default=0)),
                ('sharable', models.BooleanField(default=False)),
                ('sharer_passengers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', help_text='Ride status', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_driver', to='myapp.MyUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_owner', to='myapp.MyUser')),
                ('sharer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_sharer', to='myapp.MyUser')),
            ],
        ),
    ]
