# Generated by Django 3.0.3 on 2020-02-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='owner_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
